In [1]:
#for pandas
import pandas as pd

In [2]:
#for numpy
import numpy as np

In [3]:
#for matplotlib
import matplotlib.pyplot as plt

In [4]:
#for scipy
import scipy.io as sci

In [5]:
#function to calculate hypothesis function i.e. 1/1+exp(z)
def gz(barry):
    hey=np.exp((-1)*barry)+1
    heytt=1/hey
    return heytt

In [6]:
#location of file containing data
datafileloc="C:/Users/RitKat/Desktop/Projects_Flash/Done using Python_Andrew_Ng_Coursera/Week 4/machine-learning-ex3/ex3/ex3data1.mat"

In [7]:
#load data from .mat extension file
#this feature is given by scipy lib
data=sci.loadmat(datafileloc)


In [8]:
#printing loaded data
print(data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}


In [9]:
#observe data type of this loaded data file is dictionary type
print(type(data))

<class 'dict'>


In [10]:
#finding key values of this dictionary type data file
for i in data:
    print(i)

__header__
__version__
__globals__
X
y


In [11]:
#extracting values under key X and putting it to training examples input and converting to numpy array type
x=np.array(data["X"])

In [12]:
#extracting values under key y and putting it to training examples output and converting to numpy array type
y=np.array(data["y"])

In [13]:
#see
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
#printing training examples input
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
#printing training examples output
print(y)

[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]


In [16]:
#dimensions of x and y
print(x.shape)
print(y.shape)

(5000, 400)
(5000, 1)


In [17]:
#coverting to dataframe object
x=pd.DataFrame(x)

In [18]:
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [19]:
#inserting extra column of only value 1 also callled biased input column
x.insert(0,"extra",np.ones(5000))

In [20]:
#converting to numpy array type
X=x.as_matrix()

In [21]:
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
#dimensions of input training examples viz. 'm' stands for number of training examples and 'n' stands for number of
# of features(including extra added biaed feature which has value 1 throughout)
[m,n]=X.shape
print([m,n])
print(y.shape)

[5000, 401]
(5000, 1)


In [23]:
#location of file containing data
thetafileloc="C:/Users/RitKat/Desktop/Projects_Flash/Done using Python_Andrew_Ng_Coursera/Week 4/machine-learning-ex3/ex3/ex3weights.mat"

In [24]:
theta=sci.loadmat(thetafileloc)

In [25]:
for i in theta:
    print(i)

__header__
__version__
__globals__
Theta1
Theta2


In [26]:
theta1=np.array(theta["Theta1"])
theta2=np.array(theta["Theta2"])

In [27]:
print(theta1)

[[-2.25623899e-02 -1.05624163e-08  2.19414684e-09 ... -1.30529929e-05
  -5.04175101e-06  2.80464449e-09]
 [-9.83811294e-02  7.66168682e-09 -9.75873689e-09 ... -5.60134007e-05
   2.00940969e-07  3.54422854e-09]
 [ 1.16156052e-01 -8.77654466e-09  8.16037764e-09 ... -1.20951657e-04
  -2.33669661e-06 -7.50668099e-09]
 ...
 [-1.83220638e-01 -8.89272060e-09 -9.81968100e-09 ...  2.35311186e-05
  -3.25484493e-06  9.02499060e-09]
 [-7.02096331e-01  3.05178374e-10  2.56061008e-09 ... -8.61759744e-04
   9.43449909e-05  3.83761998e-09]
 [-3.50933229e-01  8.85876862e-09 -6.57515140e-10 ... -1.80365926e-06
  -8.14464807e-06  8.79454531e-09]]


In [28]:
print(theta2)

[[-0.76100352 -1.21244498 -0.10187131 -2.36850085 -1.05778129 -2.20823629
   0.56383834  1.21105294  2.21030997  0.44456156 -1.18244872  1.04289112
  -1.60558756  1.30419943  1.37175046  1.74825095 -0.23365648 -1.52014483
   1.15324176  0.10368082 -0.37207719 -0.61530019 -0.1256836  -2.27193038
  -0.71836208 -1.29690315]
 [-0.61785176  0.61559207 -1.26550639  1.85745418 -0.91853319 -0.05502589
  -0.38589806  1.29520853 -1.56843297 -0.97026419 -2.18334895 -2.85033578
  -2.07733086  1.63163164  0.3490229   1.82789117 -2.44174379 -0.8563034
  -0.2982564  -2.07947873 -1.2933238   0.89982032  0.28306578  2.31180525
  -2.46444086  1.45656548]
 [-0.68934072 -1.94538151  2.01360618 -3.12316188 -0.2361763   1.38680947
   0.90982429 -1.54774416 -0.79830896 -0.65599834  0.7353833  -2.58593294
   0.47210839  0.55349499  2.51255453 -2.4167454  -1.63898627  1.2027302
  -1.20245851 -1.83445959 -1.88013027 -0.34056098  0.23692483 -1.06137919
   1.02759232 -0.47690832]
 [-0.67832479  0.46299226  0.5849

In [29]:
print(theta1.shape)

(25, 401)


In [30]:
print(theta2.shape)

(10, 26)


In [31]:
layer2=gz(X.dot(np.transpose(theta1)))

In [32]:
layer2=pd.DataFrame(layer2)

In [33]:
print(type(layer2))

<class 'pandas.core.frame.DataFrame'>


In [34]:
print(layer2.shape)

(5000, 25)


In [35]:
layer2.insert(0,"extra",np.ones(5000))

In [36]:
print(layer2.shape)

(5000, 26)


In [37]:
layer2=layer2.as_matrix()
print(type(layer2))

<class 'numpy.ndarray'>


In [38]:
final=gz(layer2.dot(np.transpose(theta2)))

In [39]:
print(type(final))
print(final.shape)

<class 'numpy.ndarray'>
(5000, 10)


In [40]:
#calculating accuracy

In [41]:
#setting number of rightly identified input to be zero
right=0

In [42]:
#testing for each example
for i in range(0,5000):
    if (np.argmax(final[i,:])+1)==y[i]:
        right=right+1

In [43]:
acc=(right/5000)*100
print("Accuracy percentage is %f percent"%(acc))

Accuracy percentage is 97.520000 percent
