In [1]:
#we will be starting this exercise from Exercise section 1.4

In [2]:
#for pandas
import pandas as pd

In [3]:
#for numpy
import numpy as np

In [4]:
#for matplotlib
import matplotlib.pyplot as plt

In [5]:
#for scipy
import scipy.io as sci


In [6]:
#function to calculate hypothesis function i.e. 1/1+exp(z)
def gz(theta,x):
    hey=x.dot(theta)
    hey=np.exp((-1)*hey)+1
    heytt=1/hey
    return heytt

In [7]:
#function to calculate error
def compute_cost(theta,x,y,m,lambo=0):
    h=gz(theta,x)
    lol=((-1)*y*np.log(h))-((1-y)*np.log(1-h))
    goku=(1/m)*np.sum(lol,axis=0)
    goku=goku+lambo*np.sum(theta*theta)
    return goku

In [8]:
#function to predict which class it is...by choosing class that has maximum probabilistic value
def predict(theta,x):
    hey=gz(theta,x)
    ind=np.argmax(hey)
    return ind

In [9]:
#location of file containing data
datafileloc="C:/Users/RitKat/Desktop/Projects_Flash/Done using Python_Andrew_Ng_Coursera/Week 4/machine-learning-ex3/ex3/ex3data1.mat"

In [10]:
#load data from .mat extension file
#this feature is given by scipy lib
data=sci.loadmat(datafileloc)


In [11]:
#printing loaded data
print (data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}


In [12]:
#observe data type of this loaded data file is dictionary type
print(type(data))

<class 'dict'>


In [13]:
#finding key values of this dictionary type data file
for i in data:
    print(i)

__header__
__version__
__globals__
X
y


In [14]:
#extracting values under key X and putting it to training examples input and converting to numpy array type
x=np.array(data["X"])

In [15]:
#extracting values under key y and putting it to training examples output and converting to numpy array type
y=np.array(data["y"])

In [16]:
#see
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
#printing training examples input
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
#printing training examples output
print(y)

[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]


In [19]:
#dimensions of x and y
print(x.shape)
print(y.shape)

(5000, 400)
(5000, 1)


In [20]:
#coverting to dataframe object
x=pd.DataFrame(x)

In [21]:
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [22]:
#inserting extra column of only value 1 also callled biased input column
x.insert(0,"extra",np.ones(5000))

In [23]:
#converting to numpy array type
X=x.as_matrix()

In [24]:
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
#dimensions of input training examples viz. 'm' stands for number of training examples and 'n' stands for number of
# of features(including extra added biaed feature which has value 1 throughout)
[m,n]=X.shape
print([m,n])
print(y.shape)

[5000, 401]
(5000, 1)


In [26]:
#making new training output examples array which is of boolean type and of different dimension 
#than its original or conventional form,,in iterms of dimensions
Y=np.zeros((m,10))

In [27]:
print(Y.shape)

(5000, 10)


In [28]:
#0th column of this new Y matrix represents vector in which elemnt is 1 if corresponding element in y is =10
#1st column of this new Y matrix represents vector in which elemnt is 1 if corresponding element in y is =1
#2nd column of this new Y matrix represents vector in which elemnt is 1 if corresponding element in y is =2
#                                             .
#                                             .
#                                             .
#9th column of this new Y matrix represents vector in which elemnt is 1 if corresponding element in y is =9
for i in range(1,10):
    for flash in range(0,m):
        if y[flash]==i:
          Y[flash,i]=1

for flash in range(0,m):
    if y[flash]==10:
        Y[flash,0]=1

In [29]:
#initializing theta to new zero
theta=np.zeros((n,10))

In [30]:
#setting number of iterationson gradient descent and learning rate and regularization parameter
iterations=10000
alpha=0.001
lambo=0
ite=[i in range(0,iterations+1)]

In [31]:
#performing gradient descent classification class wise...like running for parameter that identify 0
#the running for parameters that identify 1
#and so on
for i in range(0,10):
    for xt in range(0,iterations):
      theta[:,i]=theta[:,i]*(1-(lambo/m))-(alpha/m)*((np.transpose(X).dot(gz(theta[:,i],X)-Y[:,i])))

In [32]:
#final learnt theta values
print(theta)

[[-3.31082241e-01 -1.03136353e-01 -3.01373036e-01 ... -1.97111581e-01
  -4.03987615e-01 -2.72389644e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.84570101e-05  7.52993939e-07  3.84144548e-05 ... -6.38666633e-06
  -4.06874695e-06 -4.18950926e-06]
 [ 3.76055493e-07  1.11072315e-07 -3.59674944e-06 ...  6.62814022e-07
   3.12671400e-07  3.30787434e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]


In [39]:
#after running some more 300000 or so iterations of this
#we can now predict
#with function predict()....

#you can enter a new x [do not forget to add 1 in begging of x]and get value of y 